/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteLayoutRouteRouteImport } from './routes/_protectedRouteLayout/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as ProtectedRouteLayoutTasksRouteImport } from './routes/_protectedRouteLayout/tasks'
import { Route as ProtectedRouteLayoutInboxRouteImport } from './routes/_protectedRouteLayout/inbox'
import { Route as AuthLayoutAuthRegistrationRouteImport } from './routes/_authLayout/auth/registration'
import { Route as AuthLayoutAuthLoginRouteImport } from './routes/_authLayout/auth/login'

const ProtectedRouteLayoutRouteRoute =
  ProtectedRouteLayoutRouteRouteImport.update({
    id: '/_protectedRouteLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteLayoutTasksRoute =
  ProtectedRouteLayoutTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ProtectedRouteLayoutRouteRoute,
  } as any)
const ProtectedRouteLayoutInboxRoute =
  ProtectedRouteLayoutInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => ProtectedRouteLayoutRouteRoute,
  } as any)
const AuthLayoutAuthRegistrationRoute =
  AuthLayoutAuthRegistrationRouteImport.update({
    id: '/auth/registration',
    path: '/auth/registration',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/inbox': typeof ProtectedRouteLayoutInboxRoute
  '/tasks': typeof ProtectedRouteLayoutTasksRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/registration': typeof AuthLayoutAuthRegistrationRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof ProtectedRouteLayoutInboxRoute
  '/tasks': typeof ProtectedRouteLayoutTasksRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/registration': typeof AuthLayoutAuthRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_protectedRouteLayout': typeof ProtectedRouteLayoutRouteRouteWithChildren
  '/_protectedRouteLayout/inbox': typeof ProtectedRouteLayoutInboxRoute
  '/_protectedRouteLayout/tasks': typeof ProtectedRouteLayoutTasksRoute
  '/_authLayout/auth/login': typeof AuthLayoutAuthLoginRoute
  '/_authLayout/auth/registration': typeof AuthLayoutAuthRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/inbox' | '/tasks' | '/auth/login' | '/auth/registration'
  fileRoutesByTo: FileRoutesByTo
  to: '/inbox' | '/tasks' | '/auth/login' | '/auth/registration'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_protectedRouteLayout'
    | '/_protectedRouteLayout/inbox'
    | '/_protectedRouteLayout/tasks'
    | '/_authLayout/auth/login'
    | '/_authLayout/auth/registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  ProtectedRouteLayoutRouteRoute: typeof ProtectedRouteLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protectedRouteLayout': {
      id: '/_protectedRouteLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedRouteLayout/tasks': {
      id: '/_protectedRouteLayout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ProtectedRouteLayoutTasksRouteImport
      parentRoute: typeof ProtectedRouteLayoutRouteRoute
    }
    '/_protectedRouteLayout/inbox': {
      id: '/_protectedRouteLayout/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ProtectedRouteLayoutInboxRouteImport
      parentRoute: typeof ProtectedRouteLayoutRouteRoute
    }
    '/_authLayout/auth/registration': {
      id: '/_authLayout/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthLayoutAuthRegistrationRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/auth/login': {
      id: '/_authLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutAuthLoginRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutAuthLoginRoute: typeof AuthLayoutAuthLoginRoute
  AuthLayoutAuthRegistrationRoute: typeof AuthLayoutAuthRegistrationRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutAuthLoginRoute: AuthLayoutAuthLoginRoute,
  AuthLayoutAuthRegistrationRoute: AuthLayoutAuthRegistrationRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface ProtectedRouteLayoutRouteRouteChildren {
  ProtectedRouteLayoutInboxRoute: typeof ProtectedRouteLayoutInboxRoute
  ProtectedRouteLayoutTasksRoute: typeof ProtectedRouteLayoutTasksRoute
}

const ProtectedRouteLayoutRouteRouteChildren: ProtectedRouteLayoutRouteRouteChildren =
  {
    ProtectedRouteLayoutInboxRoute: ProtectedRouteLayoutInboxRoute,
    ProtectedRouteLayoutTasksRoute: ProtectedRouteLayoutTasksRoute,
  }

const ProtectedRouteLayoutRouteRouteWithChildren =
  ProtectedRouteLayoutRouteRoute._addFileChildren(
    ProtectedRouteLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  ProtectedRouteLayoutRouteRoute: ProtectedRouteLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
